name: Build and Push Caddy Image

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger

jobs:
  check-update:
    runs-on: ubuntu-latest
    permissions:
      packages: read  # Required for pulling manifests from GHCR
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for upstream update
        id: check
        uses: lucacome/docker-image-update-checker@v3
        with:
          base-image: caddy:alpine
          image: ghcr.io/${{ github.repository_owner }}/docker-caddy:latest
          platforms: linux/amd64,linux/arm64

  build-push:
    needs: check-update
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'schedule' || needs.check-update.outputs.needs-updating == 'true' }}
    permissions:
      packages: write  # For pushing to GHCR
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-platform
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/docker-caddy:latest
          platforms: linux/amd64,linux/arm64
